
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-app
  name: hello-deployment
  annotations:
          link.argocd.argoproj.io/external-link: https://hub.docker.com/repository/docker/lucaboscato/hello-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      imagePullSecrets:
      - name: regcred1
      containers:
      - name: hello-deployment
        image: lucaboscato/hello-app:v1
        imagePullPolicy: Always
