apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-app
  name: hello-app-service
  namespace: default
spec:
  ports:
  - port: 6000
    protocol: TCP
    targetPort: 5000
  selector:
    app: hello-app
  type: NodePort
